nav:

projects_url: http://github.com/gabithume

customize:
    gravatar:
        email:
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon:
      desktop:
        url: /images/favicon.ico
        gravatar: false
    social_links:
        # github: /
        # twitter: /
        # facebook: /
        # linkedin: /
    show_all_posts: false
    post_count: 5
    highlight: monokai

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus: